### ISSUE TITLE
Silence console log messages

### ISSUE THREAD

**Issue by jamesmosier** [gajus/write-file-webpack-plugin#43]
While using `write-file-webpack-plugin`, the console is a bit noisy with messages being outputted. When running `webpack` or `webpack-dev-server` (or even when creating a `stats.json` file) I see this in my console:

```
[08:51:58] [write-file-webpack-plugin] options { exitOnErrors: true,
  force: false,
  log: true,
  test: null,
  useHashIndex: true }
[08:52:34] [write-file-webpack-plugin] compiler.outputFileSystem is "NodeOutputFileSystem".
```

Is there any way these could be silenced? Even optionally?

**Comment by gajus** [comment]
This should fix it.

**Comment by jamesmosier** [comment]
Awesome, thanks @gajus. Will you be publishing a new npm package version soon?

**Comment by gajus** [comment]
It has been published.

**Comment by jamesmosier** [comment]
Does the version have to be bumped @gajus? It is still listed as 4.0.2, which npm still thinks was last published "2 months ago". I'm still seeing the console log messages and even deleted then re-added the module via an `npm install`

**Comment by gajus** [comment]
My mistake. Published v4.1.0

https://github.com/gajus/write-file-webpack-plugin/tree/v4.1.0
